/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWizardRouteImport } from './routes/_layout/wizard'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutPortfolioRouteImport } from './routes/_layout/portfolio'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutPortfolioTailorIdRouteImport } from './routes/_layout/portfolio.$tailorId'
import { Route as LayoutInvoiceOrderIdRouteImport } from './routes/_layout/invoice.$orderId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWizardRoute = LayoutWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfolioRoute = LayoutPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfolioTailorIdRoute = LayoutPortfolioTailorIdRouteImport.update({
  id: '/$tailorId',
  path: '/$tailorId',
  getParentRoute: () => LayoutPortfolioRoute,
} as any)
const LayoutInvoiceOrderIdRoute = LayoutInvoiceOrderIdRouteImport.update({
  id: '/invoice/$orderId',
  path: '/invoice/$orderId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof LayoutAdminRoute
  '/orders': typeof LayoutOrdersRoute
  '/portfolio': typeof LayoutPortfolioRouteWithChildren
  '/profile': typeof LayoutProfileRoute
  '/wizard': typeof LayoutWizardRoute
  '/invoice/$orderId': typeof LayoutInvoiceOrderIdRoute
  '/portfolio/$tailorId': typeof LayoutPortfolioTailorIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof LayoutAdminRoute
  '/orders': typeof LayoutOrdersRoute
  '/portfolio': typeof LayoutPortfolioRouteWithChildren
  '/profile': typeof LayoutProfileRoute
  '/wizard': typeof LayoutWizardRoute
  '/': typeof LayoutIndexRoute
  '/invoice/$orderId': typeof LayoutInvoiceOrderIdRoute
  '/portfolio/$tailorId': typeof LayoutPortfolioTailorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/portfolio': typeof LayoutPortfolioRouteWithChildren
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/wizard': typeof LayoutWizardRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/invoice/$orderId': typeof LayoutInvoiceOrderIdRoute
  '/_layout/portfolio/$tailorId': typeof LayoutPortfolioTailorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/orders'
    | '/portfolio'
    | '/profile'
    | '/wizard'
    | '/invoice/$orderId'
    | '/portfolio/$tailorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/admin'
    | '/orders'
    | '/portfolio'
    | '/profile'
    | '/wizard'
    | '/'
    | '/invoice/$orderId'
    | '/portfolio/$tailorId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/admin'
    | '/_layout/orders'
    | '/_layout/portfolio'
    | '/_layout/profile'
    | '/_layout/wizard'
    | '/_layout/'
    | '/_layout/invoice/$orderId'
    | '/_layout/portfolio/$tailorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wizard': {
      id: '/_layout/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof LayoutWizardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio': {
      id: '/_layout/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof LayoutPortfolioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio/$tailorId': {
      id: '/_layout/portfolio/$tailorId'
      path: '/$tailorId'
      fullPath: '/portfolio/$tailorId'
      preLoaderRoute: typeof LayoutPortfolioTailorIdRouteImport
      parentRoute: typeof LayoutPortfolioRoute
    }
    '/_layout/invoice/$orderId': {
      id: '/_layout/invoice/$orderId'
      path: '/invoice/$orderId'
      fullPath: '/invoice/$orderId'
      preLoaderRoute: typeof LayoutInvoiceOrderIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutPortfolioRouteChildren {
  LayoutPortfolioTailorIdRoute: typeof LayoutPortfolioTailorIdRoute
}

const LayoutPortfolioRouteChildren: LayoutPortfolioRouteChildren = {
  LayoutPortfolioTailorIdRoute: LayoutPortfolioTailorIdRoute,
}

const LayoutPortfolioRouteWithChildren = LayoutPortfolioRoute._addFileChildren(
  LayoutPortfolioRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutPortfolioRoute: typeof LayoutPortfolioRouteWithChildren
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutWizardRoute: typeof LayoutWizardRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutInvoiceOrderIdRoute: typeof LayoutInvoiceOrderIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutPortfolioRoute: LayoutPortfolioRouteWithChildren,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutWizardRoute: LayoutWizardRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutInvoiceOrderIdRoute: LayoutInvoiceOrderIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
